# Generated by Django 3.2.9 on 2021-12-03 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='pics_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Image/'),
            preserve_default=False,
        ),
    ]
